language: node_js
node_js:
- 12.16.1

install: npm install
script: gatsby build

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
    provider: s3
    access_key_id: $S3_ACCESS_KEY_ID # declared in Travis repo settings
    secret_access_key: $S3_SECRET_KEY
    bucket: about.blank.no
    region: eu-central-1
    skip_cleanup: true
    local-dir: _site
    acl: public_read
    detect_encoding: true
