language: ruby
rvm:
- 2.2.5

script: jekyll build
after_success: s3_website push

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
