language: node_js
node_js:
    - "12.16.1"

python:
    - "3.7"

install: 
    - npm install
    - pip install --user awscli
    
script: npm run build

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: about.blank.no
    region: eu-central-1
    skip_cleanup: true
    local-dir: public
    acl: public_read
    detect_encoding: true

after_deploy:
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"