language: ruby
rvm:
- 2.2.5

script: bundle exec jekyll build

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
    provider: s3
    access_key_id: $S3_ACCESS_KEY_ID # declared in Travis repo settings
    secret_access_key: $S3_SECRET_KEY
    bucket: about.blankoslo.no
    region: eu-central-1
    skip_cleanup: true
    local-dir: _site
    acl: public_read
    detect_encoding: true
